# Generated by Django 4.0.4 on 2022-04-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0002_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(blank=True, to='TESTTASK.genre'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
