# Generated by Django 4.0.4 on 2022-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0003_alter_books_genres_alter_books_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='valute_currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(verbose_name='Дата')),
                ('usd_price', models.FloatField(verbose_name='Курс доллара')),
                ('jpy_price', models.FloatField(verbose_name='Курс йены')),
                ('eur_price', models.FloatField(verbose_name='Курс евро')),
            ],
        ),
    ]
