# Generated by Django 4.0.4 on 2022-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0005_rename_valute_currency_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название валюты')),
                ('symbol', models.CharField(max_length=1, verbose_name='Символ')),
            ],
        ),
    ]
