# Generated by Django 4.0.4 on 2022-05-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0006_currencyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(verbose_name='Валюта')),
                ('at', models.DateField(verbose_name='На дату')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Значение')),
                ('quoted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TESTTASK.currencyname')),
            ],
        ),
    ]
