# Generated by Django 4.0.4 on 2022-05-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0007_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='TESTTASK.currencyname'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='quoted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted', to='TESTTASK.currencyname'),
        ),
    ]
