# Generated by Django 4.0.4 on 2022-05-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0008_alter_exchangerate_base_alter_exchangerate_quoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='currency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='TESTTASK.currencyname'),
        ),
    ]
