# Generated by Django 4.0.4 on 2022-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0011_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Значение'),
        ),
    ]
