# Generated by Django 4.0.4 on 2022-05-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0012_alter_exchangerate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Значение'),
        ),
    ]
