# Generated by Django 4.0.4 on 2022-05-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0014_alter_books_price_alter_exchangerate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Значение'),
        ),
    ]
