# Generated by Django 4.0.4 on 2022-05-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0015_alter_books_price_alter_exchangerate_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('key', models.CharField(max_length=100, null=True, verbose_name='Код')),
            ],
        ),
    ]
