# Generated by Django 4.0.4 on 2022-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTTASK', '0017_alter_exchangerate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=100, null=True, verbose_name='Токен'),
        ),
    ]
